### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by Rm1n90** [cioppaanthony/rt-sbs#2]
Hey @cioppaanthony, 

Nice work! When will you release the source code? 

Best,

**Comment by cioppaanthony** [comment]
Hi, Thank you ! 

The code will be released very soon. I don't have an exact release date, but I expect it to be out by the end of September. I Hope that is good for you.

Best,

**Comment by Rm1n90** [comment]
Hey @cioppaanthony,
Perfect! Just a question, I was watching your video in your YouTube channel and you indicated that you have reached to 25FPS. I wanted to know what was the input video resolution?  Have you tried on 1080p video, if so, what FPS did you achieve?

**Comment by cioppaanthony** [comment]
Great question. 

Actually the framerate is entirely dictated by the BGS algorithm. In the case of ViBe it runs at a high framerates, even on 1080p videos (I don't remember the exact number, but I can check it out). 

Then, you simply have to choose your semantic framerate based on the semantic segmentation network that you are using. For example PSPNet might run at 5 fps on your workstation. It does not matter if it is not real time since this semantic framerate does not affect the overall framerate of your method, as it is combined asynchronously with the BGS algorithm.

I hope this helps.

**Comment by Auth0rM0rgan** [comment]
Hey @cioppaanthony, 
Amazing work! Did you decide when are you going to release the code? Thanks.

**Comment by Auth0rM0rgan** [comment]
Hey @cioppaanthon,
Amazing work! When are you going to release the code? Thanks.

**Comment by cioppaanthony** [comment]
Hi, Thanks for your interest!
I am currently waiting for the authorization from my university regarding the license to use. I am very sorry for the delay, I was hoping to get a response from them by the end of the summer. I should get a response next week hopefully.

**Comment by Auth0rM0rgan** [comment]
That's great! hope you can release the source code this week. Waiting... :)

**Comment by cioppaanthony** [comment]
The code is now released. I am very sorry for the delay... 
I hope that it will run smoothly. Don't hesitate to provide feedbacks otherwise ! :-)
