### ISSUE TITLE
not enough memory

### ISSUE THREAD

**Issue by batman47steam** [cioppaanthony/rt-sbs#6]
Hi, I am very interested in your research, and recently I tried to run the source code myself, but came into some questions, 
it said that

>   File "./main-rtsbs.py", line 48, in <module>
    video_original = torch.from_numpy(video_original).transpose(1,3).transpose(2,3).type(torch.float)
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:79] data. DefaultCPUAllocator: not enough memory: you tried to allocate 29030400000 bytes.

and i thought may be I should change the batchsize or epochs, but i didn't find them.
do you have any solutions for this ?
thanks for the answering

**Comment by cioppaanthony** [comment]
Hi @batman47steam,

Thank you for your interest in our work.
The provided code is simply a benchmarking code meant to run on the CDNet dataset only.

The error you have is due to the fact that the video is loaded entirely in memory for this code, and you are probably trying to load a too long video (hence the not enough memory error).

We did not share the code meant to run on any video since the technology is patented.
However, you have all information in this repository to re-implement it to run on any video.

I hope this helps. :-)

**Comment by batman47steam** [comment]
ok, I understand now, Thank you for the answering
